"""Initial migration

Revision ID: dbe274a79acd
Revises: 26f3b88ab1db
Create Date: 2026-09-07 12:31:01.108561
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dbe274a79acd'
down_revision: Union[str, Sequence[str], None] = '26f3b88ab1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
